version: "3.8"

services:
  db:
    image: postgres
    container_name: db_bitcoin_monitoring
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app_bitcoin_monitoring
    restart: unless-stopped
    env_file:
      - .env-non-dev
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata: